Link mesh files for visual and collision instead of creating indexed face sets
cyberbotics/urdf2webots pull request #133
Opened 2021-10-18 10:27 UTC by BenjaminHug8

This PR is for linking the mesh files instead of transforming them into index face sets when converting URDF to PROTO, thus the PROTO files are way more shorter and Webots can load faster.

2021-11-05 16:20 UTC, BenjaminHug8 commented
There is code in commentary that I will delete once you approved (maybe should we keep it) ?

2021-11-05 16:24 UTC, BenjaminHug8 commented
I just noticed one thing in Human.proto, the closing `}` is not correctly indented, I am on it.

2021-11-05 16:31 UTC, omichel commented
> There is code in commentary that I will delete once you approved (maybe should we keep it) ?

Yes, we should delete it.

2021-11-05 16:52 UTC, BenjaminHug8 commented
Ok I removed the code in commentaries and check once the code, so this PR should be ok now.

I let you @omichel do a final check with the review.

2021-11-05 16:59 UTC, omichel requested changes
It looks good to me. Only a few minor things.

2021-11-05 16:59 UTC, omichel commented on urdf2webots/parserURDF.py
> +        self.url = ""
We prefer single quotes:
```suggestion
        self.url = ''
```

2021-11-05 16:59 UTC, omichel commented on urdf2webots/parserURDF.py
> +                    collision.geometry.mesh.url = "\"" + meshfile + "\""
```suggestion
                    collision.geometry.mesh.url = '"' + meshfile + '"'
```

2021-11-08 10:11 UTC, omichel requested changes

2021-11-08 10:11 UTC, omichel commented on urdf2webots/parserURDF.py
> +                    visual.geometry.mesh.url = "\"" + meshfile + "\""
Missed that one:
```suggestion
                    visual.geometry.mesh.url = '"' + meshfile + '"'
```

2021-11-08 10:11 UTC, omichel commented on urdf2webots/writeProto.py
> +                proto.write((shapeLevel + 1) * indent + 'geometry DEF %s Mesh {\n' % (visualNode.geometry.defName))
I believe these extra parenthesis are not needed:
```suggestion
                proto.write((shapeLevel + 1) * indent + 'geometry DEF %s Mesh {\n' % visualNode.geometry.defName)
```

2021-11-08 14:52 UTC, omichel commented
After this change, it seems that the following options are now obsolete: `--disable-mesh-optimization` `--multi-file`. We should probably remove them and update the Readme.md accordingly.

2021-11-09 08:48 UTC, BenjaminHug8 commented
> After this change, it seems that the following options are now obsolete: `--disable-mesh-optimization` `--multi-file`. We should probably remove them and update the Readme.md accordingly.

I also remove `Trimesh` as it was used before for the conversion of mesh into index face set.

2021-11-09 09:13 UTC, omichel requested changes

2021-11-09 09:13 UTC, omichel commented on urdf2webots/writeProto.py
>  meshFilesPath = None
This one seems to be useless now:
```suggestion
```

2021-11-09 09:16 UTC, BenjaminHug8 commented
Should I update the `Readme.md` to state that we removed the 2 options and that now we are directly linking the meshes instead or is it not necessary ?

2021-11-09 09:26 UTC, omichel commented
I believe we should introduce a CHANGELOG.md file at the top level and start logging this kind of changes under version numbers.

2021-11-09 09:31 UTC, omichel commented
> I believe we should introduce a CHANGELOG.md file at the top level and start logging this kind of changes under version numbers.

No, that's not a good idea as it seems there is already some automatic generation of change log, see the [releases page](https://github.com/cyberbotics/urdf2webots/releases).
So we should simply ensure this automatic change log contains clear information about the change (thus the title of this PR is probably super important).

2021-11-09 10:00 UTC, BenjaminHug8 commented
> > I believe we should introduce a CHANGELOG.md file at the top level and start logging this kind of changes under version numbers.
> 
> No, that's not a good idea as it seems there is already some automatic generation of change log, see the [releases page](https://github.com/cyberbotics/urdf2webots/releases). So we should simply ensure this automatic change log contains clear information about the change (thus the title of this PR is probably super important).

So can we just have to merge this PR and prepare for a new release ?
I am just wondering why we get from version `1.0.9` to `10.0.10` ?

2021-11-09 10:02 UTC, omichel commented
> So can we just have to merge this PR and prepare for a new release?

Yes. That's probably a new GitHub feature that was not available before 10.0.10 or that we didn't enable when making the previous releases.

2021-11-09 10:05 UTC, omichel approved these changes
Thank you.

2021-11-09 10:06 UTC, merged