Change the link for the base_link file for the tutorial kuka
cyberbotics/urdf2webots pull request #138
Opened 2021-11-16 17:07 UTC by BenjaminHug8

I changed the file `base_link` int the Kuka tutorial as it had multiple occurrences of the same id for cameras and lights, thus when we imported the PROTO in Webots the `base` was showing errors.

Solve partially #137

2021-11-22 09:51 UTC, joachimhgg requested changes

2021-11-22 09:51 UTC, joachimhgg commented on docs/tutorial.md
> +[base_link.dae](./assets/files/base_link.dae)
maybe add a command line as (need to fix the paths):
`cp ./assets/files/base_link.dae kuka_experimental/kuka_lbr_iiwa_support/meshes/lbr_iiwa_14_r820/visual/base_link.dae`

2021-12-01 09:13 UTC, omichel commented
Can we merge this one?

2021-12-01 09:15 UTC, BenjaminHug8 commented
Yes of course.

2021-12-01 09:15 UTC, merged